dist : bionic
sudo: false
cache: false
language: android

jdk:
  - openjdk11

matrix:
  include:
    - jdk: openjdk11
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
  allow_failures:
    - jdk: openjdk11

android:
    components:
        - tools
        - build-tools-29.0.3
        - android-29
        - extra-google-m2repository
        - extra-android-m2repository

script:
    - TERM=dumb ./gradlew lint testDebugUnitTest jacocoTestReport

before_install:
    - chmod +x gradlew
    - yes | sdkmanager "platforms;android-29"

after_success:
    - bash <(curl -s https://codecov.io/bash)
