language: android
sudo: false
jdk: oraclejdk8
cache: false

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3

android:
  components:
    - tools
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - TERM=dumb ./gradlew lint testDebugUnitTest jacocoTestReport

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"

after_success:
  - bash <(curl -s https://codecov.io/bash)
