sudo: false
cache: false
language: android
jdk: openjdk11
dist : trusty
matrix:
  include:
    - jdk: openjdk11
  allow_failures:
    - env: JDK='OpenJDK 11'
android:
    components:
        - tools
        - build-tools-30.0.2
        - android-30
        - extra-google-m2repository
        - extra-android-m2repository
script:
    - TERM=dumb ./gradlew lint testDebugUnitTest jacocoTestReport
before_install:
    - chmod +x gradlew
    - yes | sdkmanager "platforms;android-30"
after_success:
    - bash <(curl -s https://codecov.io/bash)
