name: Android CI
on: [push, pull_request]
jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: lint
        run: bash ./gradlew lintDebug --stacktrace
      - name: unit tests
        run: bash ./gradlew testDebugUnitTest --stacktrace
      - name: coverage
        run: bash ./gradlew jacocoTestCoverageVerification --stacktrace
      - name: Reports
        uses: actions/upload-artifact@v3
        with:
          path: reports
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
